HBW-312 Add i18n for business processes
latera/homs pull request #510
Opened 2020-10-21 16:21 UTC by TimAle

2020-10-21 16:22 UTC, TimAle commented on config/application.rb
> +    config.cache_store = :mem_cache_store, ENV['MEMCACHED_URL'] || '127.0.0.1'
Thad produced deprecation warning 
```
DEPRECATION: :dalli_store will be removed in Dalli 3.0. Use Rails' official :mem_cache_store instead.
```

2020-10-29 15:28 UTC, sugarfree1 requested changes

2020-10-29 15:28 UTC, sugarfree1 commented on hbw/app/javascript/packs/hbw/components/form/string.js.jsx
> +                                className={`${!valid && 'tooltip-red'}`}/>;
```cx({ 'tooltip-red': !valid })```

2020-11-03 12:33 UTC, sugarfree1 approved these changes

2020-11-03 12:33 UTC, merged