WIP HBW-149 Don't validate hidden and disabled fields
latera/homs pull request #514
Opened 2020-11-03 00:11 UTC by vladdoncheg

2020-11-05 15:32 UTC, TimAle requested changes

2020-11-05 15:32 UTC, TimAle commented on hbw/app/javascript/packs/hbw/components/shared/hoc/validations.js
> +  const isAvailable = () => !props.hidden && !props.disabled;
Why it should be a function?

2020-11-05 15:32 UTC, TimAle commented on hbw/app/javascript/packs/hbw/components/form/string.js.jsx
> +
Should you really check this here **and** and line 95?

2020-11-05 15:43 UTC, vladdoncheg commented on hbw/app/javascript/packs/hbw/components/shared/hoc/validations.js
> +  const isAvailable = () => !props.hidden && !props.disabled;
Sure not to be

2020-11-06 10:16 UTC, TimAle approved these changes

2020-11-06 10:17 UTC, merged