HOMS-312 Add custom view for files to order data
latera/homs pull request #575
Opened 2021-07-05 11:16 UTC by kompl

2021-07-05 16:08 UTC, TimAle requested changes
Can I ask you to take a resulting screenshot?

2021-07-05 16:08 UTC, TimAle commented on app/helpers/orders_helper.rb
> +    if value.to_s.present?
Why `to_s`?

2021-07-06 05:46 UTC, kompl commented
> Can I ask you to take a resulting screenshot?

![Screenshot 2021-07-06 at 08 45 27](https://user-images.githubusercontent.com/66908882/124548617-a0a99280-de36-11eb-966f-7f026f002d23.png)

2021-07-06 12:41 UTC, TimAle approved these changes

2021-07-06 12:41 UTC, merged